### ISSUE TITLE
感谢大佬的开发，有一个功能建议

### ISSUE THREAD

**Issue by DengXiangyu111** [cpython666/SubExtractor-OCR#1]
我使用这个功能是用于字幕，最后的TXT还需要分行处理，我是复制了cmd里的信息解决。
我使用表格删除重复项后发现有识别会有一些误差，无法通过重复项删除，大佬有没有解决这个问题的建议。
感谢大佬的开发，这是我最近找的最吊的OCR字幕识别方案

**Comment by cpython666** [comment]
重复项删除是通过的集合去重，所以只有两个句子完全相同的时候才会被删除。
为了解决这个缺陷，有以下几点思路：【目前仅供说明参考，近期事务繁多不会实现】
- 识别句子会出现一些空行，可以将所有的句子替换空格为空字符串，.replace(' ','')
- 一（壹）会识别为减号或者分隔符（-或—），可以统一将减号或者分隔符（-或—）替换为一（壹），.replace('—','一').replace('-','一')
- 其他特殊情况，比如相似的字都可仿照上面的思路解决 😉
